openapi: 3.0.0
info:
  title: select-repository
  version: '1.0'
  contact:
    name: Hiroyasu Matsuhisa
    url: 'https://github.com/hmatsu47'
    email: hmatsu47@gmail.com
  license:
    name: MIT
    url: 'https://github.com/hmatsu47/select-repository-app/blob/master/LICENSE'
  description: Select ECR Repository
servers:
  - url: 'http://localhost:3000'
paths:
  /setting:
    parameters: []
    post:
      summary: Create or Update Setting
      operationId: post-setting
      responses:
        '200':
          description: OK
      description: Create or update setting.
      requestBody:
        $ref: '#/components/requestBodies/Setting'
    get:
      summary: Retrieve Setting
      operationId: get-setting
      responses:
        '200':
          $ref: '#/components/responses/Setting'
      x-internal: false
      description: Retrieve setting.
  /repositories:
    parameters: []
    get:
      summary: List Repositories
      operationId: get-repositories
      responses:
        '200':
          $ref: '#/components/responses/Repository'
      description: List repositories.
  '/images/{repository_uri}':
    get:
      summary: List Images
      responses:
        '200':
          $ref: '#/components/responses/Image'
      operationId: get-images
      description: List images.
    parameters:
      - $ref: '#/components/parameters/repository_uri'
components:
  schemas:
    Setting:
      title: Setting
      type: object
      description: Release setting
      x-examples: {}
      x-internal: false
      properties:
        image_uri:
          type: string
        release_at:
          type: string
        is_released:
          type: boolean
      required:
        - image_uri
        - release_at
        - is_released
    Repository:
      title: Repository
      x-stoplight:
        id: a5hmmb5rdowb8
      x-internal: false
      description: Repository
      type: object
      properties:
        name:
          type: string
        uri:
          type: string
      required:
        - name
        - uri
    Image:
      title: Image
      x-stoplight:
        id: 80mchgsyg9n8w
      type: object
      x-internal: false
      description: Image
      properties:
        url:
          type: string
        tags:
          type: array
          items:
            type: string
        size:
          type: number
        repository_name:
          type: string
        digest:
          type: string
        pushed_at:
          type: string
      required:
        - url
        - tags
        - size
        - repository_name
        - digest
        - pushed_at
  parameters:
    repository_uri:
      name: repository_uri
      in: path
      required: true
      schema:
        type: string
      description: ECR Repository URI
  requestBodies:
    Setting:
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Setting'
        multipart/form-data:
          schema:
            type: object
            properties: {}
      description: Setting
  responses:
    Repository:
      description: Repository
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Repository'
    Image:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Image'
    Setting:
      description: Example response
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
        application/xml:
          schema:
            $ref: '#/components/schemas/Setting'
